# Generated by Django 5.1.7 on 2025-03-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='最佳搭配：1920*1080', upload_to='static/img/', verbose_name='幻灯片')),
                ('title', models.CharField(help_text='一级标题', max_length=200, verbose_name='标题')),
                ('content', models.CharField(help_text='二级标题', max_length=200, verbose_name='内容')),
            ],
        ),
    ]
