# Generated by Django 5.1.7 on 2025-03-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(help_text='最佳搭配：1920*1080', upload_to='media/', verbose_name='幻灯片'),
        ),
    ]
